// Generated by scripts/update_games.py. Edit PLACE_IDS there and re-run instead of editing this file.
const GAMES = [
  {
    "title": "Lucky Block Troll Tower 🍀",
    "image": "/assets/games/76128254547104.png",
    "thumb": "/assets/games/small/76128254547104.jpg",
    "plays": 80513798,
    "playing": 165,
    "universeId": 8514466390,
    "link": "https://www.roblox.com/games/76128254547104/"
  },
  {
    "title": "[X2] +1 Jump Keyboard Escape",
    "image": "/assets/games/92184831525884.png",
    "thumb": "/assets/games/small/92184831525884.jpg",
    "plays": 28975314,
    "playing": 28,
    "universeId": 9751740164,
    "link": "https://www.roblox.com/games/92184831525884/"
  },
  {
    "title": "Hide Troll Tower",
    "image": "/assets/games/91023000544333.png",
    "thumb": "/assets/games/small/91023000544333.jpg",
    "plays": 14905789,
    "playing": 36,
    "universeId": 8487827163,
    "link": "https://www.roblox.com/games/91023000544333/"
  },
  {
    "title": "Power Rangers Tycoon",
    "image": "/assets/games/15367424318.png",
    "thumb": "/assets/games/small/15367424318.jpg",
    "plays": 7929622,
    "playing": 28,
    "universeId": 5300826049,
    "link": "https://www.roblox.com/games/15367424318/"
  },
  {
    "title": "Murder Sherif Tower",
    "image": "/assets/games/81397329495359.png",
    "thumb": "/assets/games/small/81397329495359.jpg",
    "plays": 7732706,
    "playing": 42,
    "universeId": 8603679461,
    "link": "https://www.roblox.com/games/81397329495359/"
  },
  {
    "title": "Admin Abuse Tower [5 Robux]",
    "image": "/assets/games/116564894722401.png",
    "thumb": "/assets/games/small/116564894722401.jpg",
    "plays": 4431878,
    "playing": 1,
    "universeId": 8817845872,
    "link": "https://www.roblox.com/games/116564894722401/"
  },
  {
    "title": "Aura Edit Phonk Tower 🎵",
    "image": "/assets/games/89025817054592.png",
    "thumb": "/assets/games/small/89025817054592.jpg",
    "plays": 4229489,
    "playing": 6,
    "universeId": 9368467895,
    "link": "https://www.roblox.com/games/89025817054592/"
  },
  {
    "title": "Escape Logs for Brainrots!",
    "image": "/assets/games/94966213601846.png",
    "thumb": "/assets/games/small/94966213601846.jpg",
    "plays": 3953246,
    "playing": 0,
    "universeId": 9590506924,
    "link": "https://www.roblox.com/games/94966213601846/"
  },
  {
    "title": "Swing Obby for SCP!",
    "image": "/assets/games/72312037339529.png",
    "thumb": "/assets/games/small/72312037339529.jpg",
    "plays": 1535831,
    "playing": 13,
    "universeId": 9895567340,
    "link": "https://www.roblox.com/games/72312037339529/"
  },
  {
    "title": "Lucky Blocks Tower",
    "image": "/assets/games/130204173735797.png",
    "thumb": "/assets/games/small/130204173735797.jpg",
    "plays": 1049020,
    "playing": 0,
    "universeId": 9275108427,
    "link": "https://www.roblox.com/games/130204173735797/"
  },
  {
    "title": "Swing Obby for Anime Fruits!",
    "image": "/assets/games/103854049901851.png",
    "thumb": "/assets/games/small/103854049901851.jpg",
    "plays": 683956,
    "playing": 18,
    "universeId": 9867067642,
    "link": "https://www.roblox.com/games/103854049901851/"
  },
  {
    "title": "+1 Jump Crunchy Wax Escape!",
    "image": "/assets/games/71098316308533.png",
    "thumb": "/assets/games/small/71098316308533.jpg",
    "plays": 461465,
    "playing": 1,
    "universeId": 9582851977,
    "link": "https://www.roblox.com/games/71098316308533/"
  },
  {
    "title": "Escape Tsunami For Capibara",
    "image": "/assets/games/74608327682047.png",
    "thumb": "/assets/games/small/74608327682047.jpg",
    "plays": 347391,
    "playing": 0,
    "universeId": 9603527248,
    "link": "https://www.roblox.com/games/74608327682047/"
  },
  {
    "title": "+1 Jump Keyboard Escape | Candy & Choc",
    "image": "/assets/games/100011138344202.png",
    "thumb": "/assets/games/small/100011138344202.jpg",
    "plays": 253795,
    "playing": 3,
    "universeId": 10750518495,
    "link": "https://www.roblox.com/games/100011138344202/"
  },
  {
    "title": "Swing Obby for Poppy Playtime!",
    "image": "/assets/games/131959679324388.png",
    "thumb": "/assets/games/small/131959679324388.jpg",
    "plays": 79833,
    "playing": 0,
    "universeId": 9911275419,
    "link": "https://www.roblox.com/games/131959679324388/"
  },
  {
    "title": "Escape Barrel for Brainrots",
    "image": "/assets/games/136153892412083.png",
    "thumb": "/assets/games/small/136153892412083.jpg",
    "plays": 68007,
    "playing": 0,
    "universeId": 9591685628,
    "link": "https://www.roblox.com/games/136153892412083/"
  },
  {
    "title": "Dodge 67 For Brainrots",
    "image": "/assets/games/73513083912887.png",
    "thumb": "/assets/games/small/73513083912887.jpg",
    "plays": 45917,
    "playing": 0,
    "universeId": 9594019574,
    "link": "https://www.roblox.com/games/73513083912887/"
  },
  {
    "title": "Kick a Lucky Block for Soccer Legends! 🐐",
    "image": "/assets/games/90135108746968.png",
    "thumb": "/assets/games/small/90135108746968.jpg",
    "plays": 22429,
    "playing": 6,
    "universeId": 10761621939,
    "link": "https://www.roblox.com/games/90135108746968/"
  },
  {
    "title": "+1 Sticky-hand Escape! 🖐️",
    "image": "/assets/games/125743413265622.png",
    "thumb": "/assets/games/small/125743413265622.jpg",
    "plays": 3877,
    "playing": 40,
    "universeId": 10766818459,
    "link": "https://www.roblox.com/games/125743413265622/"
  }
];
