// Generated by scripts/update_games.py. Edit PLACE_IDS there and re-run instead of editing this file.
const GAMES = [
  {
    "title": "Lucky Block Troll Tower 🍀",
    "image": "assets/games/76128254547104.png",
    "plays": 80512203,
    "link": "https://www.roblox.com/games/76128254547104/"
  },
  {
    "title": "[X2] +1 Jump Keyboard Escape",
    "image": "assets/games/92184831525884.png",
    "plays": 28974705,
    "link": "https://www.roblox.com/games/92184831525884/"
  },
  {
    "title": "Hide Troll Tower",
    "image": "assets/games/91023000544333.png",
    "plays": 14905399,
    "link": "https://www.roblox.com/games/91023000544333/"
  },
  {
    "title": "Murder Sherif Tower",
    "image": "assets/games/81397329495359.png",
    "plays": 7732333,
    "link": "https://www.roblox.com/games/81397329495359/"
  },
  {
    "title": "Admin Abuse Tower [5 Robux]",
    "image": "assets/games/116564894722401.png",
    "plays": 4431875,
    "link": "https://www.roblox.com/games/116564894722401/"
  },
  {
    "title": "Aura Edit Phonk Tower 🎵",
    "image": "assets/games/89025817054592.png",
    "plays": 4229417,
    "link": "https://www.roblox.com/games/89025817054592/"
  },
  {
    "title": "+1 Jump Crunchy Wax Escape!",
    "image": "assets/games/71098316308533.png",
    "plays": 461458,
    "link": "https://www.roblox.com/games/71098316308533/"
  },
  {
    "title": "+1 Jump Keyboard Escape | Candy & Choc",
    "image": "assets/games/100011138344202.png",
    "plays": 253734,
    "link": "https://www.roblox.com/games/100011138344202/"
  },
  {
    "title": "Kick a Lucky Block for Soccer Legends! 🐐",
    "image": "assets/games/90135108746968.png",
    "plays": 22266,
    "link": "https://www.roblox.com/games/90135108746968/"
  },
  {
    "title": "+1 Sticky-hand Escape! 🖐️",
    "image": "assets/games/125743413265622.png",
    "plays": 3515,
    "link": "https://www.roblox.com/games/125743413265622/"
  }
];
