#!/usr/bin/env python3
"""Refresh games.js and game icons from Roblox.

Usage: python3 scripts/update_games.py
To add or remove a game, edit PLACE_IDS below (the number in the game's Roblox URL).
"""
import json
import pathlib
import subprocess

PLACE_IDS = [
    90135108746968,
    125743413265622,
    100011138344202,
    71098316308533,
    92184831525884,
    89025817054592,
    76128254547104,
    91023000544333,
    81397329495359,
    116564894722401,
    130204173735797,
    103854049901851,
    74608327682047,
    94966213601846,
    72312037339529,
    73513083912887,
    136153892412083,
    131959679324388,
    15367424318,
    18507991230,
    16958952795,
]

ROOT = pathlib.Path(__file__).resolve().parent.parent
ICON_DIR = ROOT / "assets" / "games"
THUMB_DIR = ICON_DIR / "small"
THUMB_PX = 200


def fetch(url):
    return subprocess.run(
        ["curl", "-sSfL", "--max-time", "20", url], check=True, capture_output=True
    ).stdout


def get_json(url):
    return json.loads(fetch(url))


def make_thumb(src, dest):
    """Small JPEG for the homepage background wall (uses macOS `sips`)."""
    subprocess.run(
        ["sips", "-s", "format", "jpeg", "-s", "formatOptions", "75", "-Z", str(THUMB_PX),
         str(src), "--out", str(dest)],
        check=True, capture_output=True,
    )


def main():
    universe_ids = [
        get_json(f"https://apis.roblox.com/universes/v1/places/{pid}/universe")["universeId"]
        for pid in PLACE_IDS
    ]
    ids = ",".join(map(str, universe_ids))
    details = {g["id"]: g for g in get_json(f"https://games.roblox.com/v1/games?universeIds={ids}")["data"]}
    icons = {
        d["targetId"]: d["imageUrl"]
        for d in get_json(
            f"https://thumbnails.roblox.com/v1/games/icons?universeIds={ids}&size=512x512&format=Png"
        )["data"]
        if d["state"] == "Completed"
    }

    THUMB_DIR.mkdir(parents=True, exist_ok=True)
    games = []
    for pid, uid in zip(PLACE_IDS, universe_ids):
        g = details.get(uid)
        if not g or not g.get("id"):
            print(f"  skipped place {pid}: private or unavailable on Roblox")
            continue
        image = thumb = ""
        if uid in icons:
            icon_path = ICON_DIR / f"{pid}.png"
            icon_path.write_bytes(fetch(icons[uid]))
            make_thumb(icon_path, THUMB_DIR / f"{pid}.jpg")
            image = f"/assets/games/{pid}.png"
            thumb = f"/assets/games/small/{pid}.jpg"
        games.append({
            "title": g["name"],
            "image": image,
            "thumb": thumb,
            "plays": g["visits"],
            "playing": g["playing"],
            "universeId": uid,
            "link": f"https://www.roblox.com/games/{pid}/",
        })
        print(f"{g['visits']:>12,}  {g['name']}")

    games.sort(key=lambda x: x["plays"], reverse=True)
    body = json.dumps(games, indent=2, ensure_ascii=False)
    (ROOT / "games.js").write_text(
        "// Generated by scripts/update_games.py. Edit PLACE_IDS there and re-run instead of editing this file.\n"
        f"const GAMES = {body};\n",
        encoding="utf-8",
    )
    print(f"\nWrote {len(games)} games to games.js")


if __name__ == "__main__":
    main()
