#!/usr/bin/env python3
"""Refresh games.js and game icons from Roblox.

Usage: python3 scripts/update_games.py
To add or remove a game, edit PLACE_IDS below (the number in the game's Roblox URL).
"""
import json
import pathlib
import subprocess

PLACE_IDS = [
    90135108746968,
    125743413265622,
    100011138344202,
    71098316308533,
    92184831525884,
    89025817054592,
    76128254547104,
    91023000544333,
    81397329495359,
    116564894722401,
]

ROOT = pathlib.Path(__file__).resolve().parent.parent
ICON_DIR = ROOT / "assets" / "games"


def fetch(url):
    return subprocess.run(
        ["curl", "-sSfL", "--max-time", "20", url], check=True, capture_output=True
    ).stdout


def get_json(url):
    return json.loads(fetch(url))


def main():
    universe_ids = [
        get_json(f"https://apis.roblox.com/universes/v1/places/{pid}/universe")["universeId"]
        for pid in PLACE_IDS
    ]
    ids = ",".join(map(str, universe_ids))
    details = {g["id"]: g for g in get_json(f"https://games.roblox.com/v1/games?universeIds={ids}")["data"]}
    icons = {
        d["targetId"]: d["imageUrl"]
        for d in get_json(
            f"https://thumbnails.roblox.com/v1/games/icons?universeIds={ids}&size=512x512&format=Png"
        )["data"]
        if d["state"] == "Completed"
    }

    ICON_DIR.mkdir(parents=True, exist_ok=True)
    games = []
    for pid, uid in zip(PLACE_IDS, universe_ids):
        g = details[uid]
        image = ""
        if uid in icons:
            (ICON_DIR / f"{pid}.png").write_bytes(fetch(icons[uid]))
            image = f"assets/games/{pid}.png"
        games.append({
            "title": g["name"],
            "image": image,
            "plays": g["visits"],
            "link": f"https://www.roblox.com/games/{pid}/",
        })
        print(f"{g['visits']:>12,}  {g['name']}")

    games.sort(key=lambda x: x["plays"], reverse=True)
    body = json.dumps(games, indent=2, ensure_ascii=False)
    (ROOT / "games.js").write_text(
        "// Generated by scripts/update_games.py. Edit PLACE_IDS there and re-run instead of editing this file.\n"
        f"const GAMES = {body};\n",
        encoding="utf-8",
    )
    print(f"\nWrote {len(games)} games to games.js")


if __name__ == "__main__":
    main()
